repos:
  # Higiene Básica
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace      # Remove espaços inúteis
      - id: end-of-file-fixer        # Garante linha vazia no final
      - id: check-added-large-files  # Bloqueia binários gigantes
      - id: check-merge-conflict     # Bloqueia marcas de conflito (<<<<)
      - id: detect-private-key       # Bloqueia arquivos id_rsa/.pem

  # Segurança de Segredos (Gitleaks)
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        # --redact: Mostra que achou um segredo, mas não imprime o valor no terminal (segurança em logs)
        args: ["--redact", "--exit-code", "1"]
